// Package-owned migrations for @corbits/chat's two product tables.
// The platform's own schema is authored and applied by @intx/db (see
// scripts/db-setup.ts); this module is the package's half of the
// install story described by the signed structure doc: "mount +
// migrations is the entire install story." Bookkeeping is deliberately
// its own table, never the platform's drizzle journal, so the chat
// package's migration history stays extractable on its own.
import postgres from "postgres";

export interface ChatMigration {
  name: string;
  sql: string;
}

/**
 * Ordered, explicit migration set for the two tables declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by drizzle
 * at apply-time) so the applied statements are exactly what is
 * reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const chatMigrations: readonly ChatMigration[] = [
  {
    name: "0001_channel_settings",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_settings" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "settings" jsonb NOT NULL,
        "updated_by" text NOT NULL,
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id")
      );
    `,
  },
  {
    name: "0002_channel_read_state",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_read_state" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "last_seen_created_at" timestamptz NOT NULL,
        "last_seen_id" text NOT NULL,
        PRIMARY KEY ("tenant_id", "channel_id", "principal_id")
      );
    `,
  },
  {
    name: "0003_channel_launch",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_launch" (
        "tenant_id" text NOT NULL,
        "instance_id" text NOT NULL,
        "folded_body" jsonb NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("instance_id")
      );
    `,
  },
  {
    name: "0004_channel_launch_noop_inference",
    sql: `
      ALTER TABLE "chat"."channel_launch"
        ADD COLUMN IF NOT EXISTS "noop_inference" boolean NOT NULL DEFAULT false;
    `,
  },
  {
    name: "0005_channel_tenancy",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_tenancy" (
        "channel_id" text NOT NULL,
        "tenant_id" text NOT NULL,
        "parent_tenant_id" text NOT NULL,
        "slug" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("channel_id"),
        UNIQUE ("tenant_id")
      );
    `,
  },
  {
    name: "0006_channel_tenancy_parent_index",
    sql: `
      CREATE INDEX IF NOT EXISTS "channel_tenancy_parent_tenant_id_idx"
        ON "chat"."channel_tenancy" ("parent_tenant_id");
    `,
  },
  {
    name: "0007_chat_bench_settings",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."chat_bench_settings" (
        "tenant_id" text NOT NULL,
        "settings" jsonb NOT NULL,
        "updated_by" text NOT NULL,
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id")
      );
    `,
  },
  // Before this rollout, `channel_settings.settings->>'chat/contextWindow'`
  // had exactly one meaning: an explicit per-channel value, read back by
  // `contextWindowOf` with a code-level fallback of 20 for any row that
  // never set the key at all. There was no bench-wide default for a
  // channel to "inherit" — every existing value already on a row is
  // therefore a real, deliberately-set override, not some default that
  // happened to get written. Introducing bench defaults must not
  // silently reinterpret those rows as "inheriting" (they were never
  // inheriting anything), so this migration leaves every row that
  // already carries the key untouched — it stays an explicit override —
  // and only touches rows with no key at all, making that absence
  // explicit as `null` (inherit) rather than continuing to rely on an
  // implicit, code-only fallback now that a real bench-wide default
  // exists to inherit from.
  {
    name: "0008_channel_context_window_explicit_inherit",
    sql: `
      UPDATE "chat"."channel_settings"
      SET "settings" = jsonb_set("settings", '{chat/contextWindow}', 'null'::jsonb)
      WHERE NOT ("settings" ? 'chat/contextWindow');
    `,
  },
  {
    name: "0009_channel_threads",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_threads" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "kind" text NOT NULL,
        "parent_message_id" text,
        "run_ref" text,
        "title" text,
        "created_at" timestamptz NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS "channel_threads_channel_idx"
        ON "chat"."channel_threads" ("tenant_id", "channel_id");
      CREATE TABLE IF NOT EXISTS "chat"."channel_thread_messages" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "thread_id" text NOT NULL,
        "message_id" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id")
      );
      CREATE INDEX IF NOT EXISTS "channel_thread_messages_thread_idx"
        ON "chat"."channel_thread_messages" ("tenant_id", "thread_id");
    `,
  },
  {
    name: "0010_block_responses",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."block_responses" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "block_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "payload" jsonb NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id", "block_id", "principal_id")
      );
      CREATE INDEX IF NOT EXISTS "block_responses_block_idx"
        ON "chat"."block_responses" ("tenant_id", "channel_id", "message_id", "block_id");
    `,
  },
  {
    name: "0011_channel_threads_parent_thread_id",
    sql: `
      ALTER TABLE "chat"."channel_threads"
        ADD COLUMN IF NOT EXISTS "parent_thread_id" text;
      CREATE INDEX IF NOT EXISTS "channel_threads_parent_thread_idx"
        ON "chat"."channel_threads" ("tenant_id", "parent_thread_id");
    `,
  },
  {
    name: "0012_message_reactions",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."message_reactions" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "emoji" text NOT NULL,
        "principal_id" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id", "emoji", "principal_id")
      );
      CREATE INDEX IF NOT EXISTS "message_reactions_message_idx"
        ON "chat"."message_reactions" ("tenant_id", "channel_id", "message_id");
    `,
  },
  {
    name: "0013_pinned_messages",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."pinned_messages" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "pinned_by" text NOT NULL,
        "pinned_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id")
      );
      CREATE INDEX IF NOT EXISTS "pinned_messages_channel_idx"
        ON "chat"."pinned_messages" ("tenant_id", "channel_id");
    `,
  },
  {
    name: "0014_channel_share",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_share" (
        "owning_tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "projected_tenant_id" text NOT NULL,
        "created_by" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("channel_id", "projected_tenant_id")
      );
      CREATE INDEX IF NOT EXISTS "channel_share_projected_idx"
        ON "chat"."channel_share" ("projected_tenant_id");
    `,
  },
  {
    name: "0015_channel_share_member",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_share_member" (
        "projected_tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "added_by" text NOT NULL,
        "added_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("projected_tenant_id", "channel_id", "principal_id")
      );
    `,
  },
  {
    name: "0016_finalized_turn_write_claim",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."finalized_turn_write_claim" (
        "tenant_id" text NOT NULL,
        "surface" text NOT NULL,
        "claim_key" text NOT NULL,
        "claimed_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "surface", "claim_key")
      );
    `,
  },
  {
    name: "0017_message_client_ids",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."message_client_ids" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "client_id" text NOT NULL,
        PRIMARY KEY ("tenant_id", "channel_id", "message_id")
      );
    `,
  },
  // Product rename (CL-6260): "channel" is retired as this package's own
  // vocabulary in favor of "workbench" — every table and column above was
  // named at creation time under the old word, so this migration is the
  // one place that carries them forward. Plain renames only: no data
  // moves, no column ever changes type, so this is a metadata-only
  // operation on Postgres and safe to run against a live table.
  {
    name: "0018_rename_channel_to_workbench",
    sql: `
      ALTER TABLE "chat"."channel_settings" RENAME TO "workbench_settings";
      ALTER TABLE "chat"."workbench_settings" RENAME COLUMN "channel_id" TO "workbench_id";

      ALTER TABLE "chat"."channel_read_state" RENAME TO "workbench_read_state";
      ALTER TABLE "chat"."workbench_read_state" RENAME COLUMN "channel_id" TO "workbench_id";

      ALTER TABLE "chat"."channel_launch" RENAME TO "workbench_launch";

      ALTER TABLE "chat"."channel_tenancy" RENAME TO "workbench_tenancy";
      ALTER TABLE "chat"."workbench_tenancy" RENAME COLUMN "channel_id" TO "workbench_id";
      ALTER INDEX "chat"."channel_tenancy_parent_tenant_id_idx" RENAME TO "workbench_tenancy_parent_tenant_id_idx";

      ALTER TABLE "chat"."channel_threads" RENAME TO "workbench_threads";
      ALTER TABLE "chat"."workbench_threads" RENAME COLUMN "channel_id" TO "workbench_id";
      ALTER INDEX "chat"."channel_threads_channel_idx" RENAME TO "workbench_threads_workbench_idx";
      ALTER INDEX "chat"."channel_threads_parent_thread_idx" RENAME TO "workbench_threads_parent_thread_idx";

      ALTER TABLE "chat"."channel_thread_messages" RENAME TO "workbench_thread_messages";
      ALTER TABLE "chat"."workbench_thread_messages" RENAME COLUMN "channel_id" TO "workbench_id";
      ALTER INDEX "chat"."channel_thread_messages_thread_idx" RENAME TO "workbench_thread_messages_thread_idx";

      ALTER TABLE "chat"."block_responses" RENAME COLUMN "channel_id" TO "workbench_id";

      ALTER TABLE "chat"."message_reactions" RENAME COLUMN "channel_id" TO "workbench_id";

      ALTER TABLE "chat"."pinned_messages" RENAME COLUMN "channel_id" TO "workbench_id";
      ALTER INDEX "chat"."pinned_messages_channel_idx" RENAME TO "pinned_messages_workbench_idx";

      ALTER TABLE "chat"."channel_share" RENAME TO "workbench_share";
      ALTER TABLE "chat"."workbench_share" RENAME COLUMN "channel_id" TO "workbench_id";
      ALTER INDEX "chat"."channel_share_projected_idx" RENAME TO "workbench_share_projected_idx";

      ALTER TABLE "chat"."channel_share_member" RENAME TO "workbench_share_member";
      ALTER TABLE "chat"."workbench_share_member" RENAME COLUMN "channel_id" TO "workbench_id";

      ALTER TABLE "chat"."message_client_ids" RENAME COLUMN "channel_id" TO "workbench_id";
    `,
  },
  // The room's own timeline (CL-6327). Messages used to be platform mail
  // read back through the platform port; they are workbench data now, and
  // this table is where they live. Everything keyed by the old mail ids —
  // thread membership, reactions, pins, client send ids, and every reply
  // thread's own parent — names messages that no longer exist, so those
  // rows go with them rather than dangling against a message store that
  // never had them. Root and delivery threads are keyed to a workbench
  // and a run ref, not to a message, and survive.
  {
    name: "0019_workbench_messages",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."workbench_messages" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "workbench_id" text NOT NULL,
        "sender_address" text NOT NULL,
        "sender_name" text,
        "sender_principal_id" text,
        "run_id" text,
        "thread_id" text,
        "parts" jsonb NOT NULL,
        "created_at" timestamptz(3) NOT NULL DEFAULT now()
      );

      CREATE INDEX IF NOT EXISTS "workbench_messages_feed_idx"
        ON "chat"."workbench_messages" ("tenant_id", "workbench_id", "created_at");

      DELETE FROM "chat"."workbench_thread_messages";
      DELETE FROM "chat"."message_reactions";
      DELETE FROM "chat"."pinned_messages";
      DELETE FROM "chat"."message_client_ids";
      DELETE FROM "chat"."block_responses";
      DELETE FROM "chat"."workbench_threads" WHERE "kind" = 'reply';
    `,
  },
  {
    // Un-fuses the room's identity from the run's. `instance_id` stops
    // meaning "the run" and starts meaning "the stable participant the
    // room addresses"; `current_run_id` names the run actually
    // executing behind it, re-pointed on every relaunch. Existing rows
    // are the identity mapping they have always implied.
    name: "0020_workbench_launch_current_run",
    sql: `
      ALTER TABLE "chat"."workbench_launch"
        ADD COLUMN IF NOT EXISTS "current_run_id" text;

      UPDATE "chat"."workbench_launch"
        SET "current_run_id" = "instance_id"
        WHERE "current_run_id" IS NULL;

      ALTER TABLE "chat"."workbench_launch"
        ALTER COLUMN "current_run_id" SET NOT NULL;

      CREATE UNIQUE INDEX IF NOT EXISTS "workbench_launch_current_run_idx"
        ON "chat"."workbench_launch" ("current_run_id");
    `,
  },
  {
    name: "0021_workbench_launch_prior_runs",
    sql: `
      ALTER TABLE "chat"."workbench_launch"
        ADD COLUMN IF NOT EXISTS "prior_run_ids" jsonb NOT NULL DEFAULT '[]'::jsonb;
    `,
  },
  {
    name: "0022_agent_turns",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."agent_turns" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "workbench_id" text NOT NULL,
        "agent_address" text NOT NULL,
        "section_run_id" text,
        "child_run_id" text NOT NULL,
        "occurrence" integer NOT NULL,
        "request_message_ids" jsonb NOT NULL,
        "reply_message_id" text,
        "status" text NOT NULL,
        "error" text,
        "started_at" timestamptz NOT NULL DEFAULT now(),
        "ended_at" timestamptz
      );

      CREATE INDEX IF NOT EXISTS "agent_turns_workbench_idx"
        ON "chat"."agent_turns" ("tenant_id", "workbench_id", "started_at");

      CREATE UNIQUE INDEX IF NOT EXISTS "agent_turns_occurrence_key"
        ON "chat"."agent_turns"
        ("tenant_id", "workbench_id", "agent_address", "occurrence");
    `,
  },
  {
    // CL-6330: the workbench-host anchor is gone — a workbench is data,
    // only invited agents have launch rows. Host rows (the anchor arm)
    // are deleted before the discriminating column is dropped.
    name: "0023_drop_workbench_host_arm",
    sql: `
      DELETE FROM "chat"."workbench_launch" WHERE "noop_inference" = true;

      ALTER TABLE "chat"."workbench_launch"
        DROP COLUMN IF EXISTS "noop_inference";
    `,
  },
  {
    name: "0024_workbench_launch_sources_digest",
    sql: `
      ALTER TABLE "chat"."workbench_launch"
        ADD COLUMN IF NOT EXISTS "sources_digest" text;
    `,
  },
  {
    // CL-7130: `ensureRootThread`/`anchoredReplyThread` used to
    // select-then-insert with no unique constraint backing the read,
    // so concurrent first writers could each insert a thread for the
    // same (workbench, kind='root') or (workbench, parent_message_id,
    // kind='reply') key. Dedupe existing duplicates — keeping the
    // oldest row per key — before the partial unique indexes below
    // make a repeat impossible: every reference to a dropped
    // duplicate's id (thread membership, message thread pointers, and
    // any reply thread anchored under a dropped duplicate root) is
    // repointed at the kept row first, so nothing is left dangling.
    name: "0025_workbench_threads_unique_key",
    sql: `
      CREATE TEMP TABLE "thread_dedupe_map" ON COMMIT DROP AS
      SELECT "id" AS "drop_id", "keep_id" FROM (
        SELECT
          "id",
          first_value("id") OVER (
            PARTITION BY "tenant_id", "workbench_id", "kind", "parent_message_id"
            ORDER BY "created_at", "id"
          ) AS "keep_id"
        FROM "chat"."workbench_threads"
        WHERE "kind" IN ('root', 'reply')
      ) "ranked"
      WHERE "id" <> "keep_id";

      UPDATE "chat"."workbench_thread_messages" "wtm"
        SET "thread_id" = "m"."keep_id"
        FROM "thread_dedupe_map" "m"
        WHERE "wtm"."thread_id" = "m"."drop_id";

      UPDATE "chat"."workbench_messages" "wm"
        SET "thread_id" = "m"."keep_id"
        FROM "thread_dedupe_map" "m"
        WHERE "wm"."thread_id" = "m"."drop_id";

      UPDATE "chat"."workbench_threads" "wt"
        SET "parent_thread_id" = "m"."keep_id"
        FROM "thread_dedupe_map" "m"
        WHERE "wt"."parent_thread_id" = "m"."drop_id";

      DELETE FROM "chat"."workbench_threads" "wt"
        USING "thread_dedupe_map" "m"
        WHERE "wt"."id" = "m"."drop_id";

      CREATE UNIQUE INDEX IF NOT EXISTS "workbench_threads_root_key"
        ON "chat"."workbench_threads" ("tenant_id", "workbench_id")
        WHERE "kind" = 'root';

      CREATE UNIQUE INDEX IF NOT EXISTS "workbench_threads_reply_key"
        ON "chat"."workbench_threads" ("tenant_id", "workbench_id", "parent_message_id")
        WHERE "kind" = 'reply';
    `,
  },
  {
    // CL-7199: `createDeliveryThread` select-then-inserted with no
    // unique constraint backing the read, same class of bug as 0025's
    // root/reply case — a redelivered routine event could insert a
    // second delivery thread for the same run. Dedupe existing
    // duplicates — keeping the oldest row per (tenant, workbench,
    // run_ref) — before the partial unique index below makes a repeat
    // impossible, repointing every reference to a dropped duplicate's
    // id first. Rows with a null `run_ref` are excluded from the
    // dedupe: the window partition below groups nulls together, but
    // the partial index treats them as distinct, so collapsing them
    // here would delete rows the index was never going to reject.
    name: "0026_workbench_threads_delivery_key",
    sql: `
      CREATE TEMP TABLE "delivery_thread_dedupe_map" ON COMMIT DROP AS
      SELECT "id" AS "drop_id", "keep_id" FROM (
        SELECT
          "id",
          first_value("id") OVER (
            PARTITION BY "tenant_id", "workbench_id", "run_ref"
            ORDER BY "created_at", "id"
          ) AS "keep_id"
        FROM "chat"."workbench_threads"
        WHERE "kind" = 'delivery' AND "run_ref" IS NOT NULL
      ) "ranked"
      WHERE "id" <> "keep_id";

      UPDATE "chat"."workbench_thread_messages" "wtm"
        SET "thread_id" = "m"."keep_id"
        FROM "delivery_thread_dedupe_map" "m"
        WHERE "wtm"."thread_id" = "m"."drop_id";

      UPDATE "chat"."workbench_messages" "wm"
        SET "thread_id" = "m"."keep_id"
        FROM "delivery_thread_dedupe_map" "m"
        WHERE "wm"."thread_id" = "m"."drop_id";

      UPDATE "chat"."workbench_threads" "wt"
        SET "parent_thread_id" = "m"."keep_id"
        FROM "delivery_thread_dedupe_map" "m"
        WHERE "wt"."parent_thread_id" = "m"."drop_id";

      DELETE FROM "chat"."workbench_threads" "wt"
        USING "delivery_thread_dedupe_map" "m"
        WHERE "wt"."id" = "m"."drop_id";

      CREATE UNIQUE INDEX IF NOT EXISTS "workbench_threads_delivery_key"
        ON "chat"."workbench_threads" ("tenant_id", "workbench_id", "run_ref")
        WHERE "kind" = 'delivery' AND "run_ref" IS NOT NULL;
    `,
  },
  {
    name: "0027_block_responses_notified_at",
    sql: `
      ALTER TABLE "chat"."block_responses"
        ADD COLUMN IF NOT EXISTS "notified_at" timestamptz,
        ADD COLUMN IF NOT EXISTS "notification_claim_token" text;
    `,
  },
  {
    // CL-6314: which workbench message a dispatch mail answers, so an
    // agent's reply inherits its source message's thread. Insert-only
    // correlation — no backfill, nothing to migrate: mails sent before
    // this landed simply have no row, and replies to them post
    // unthreaded exactly as before.
    name: "0028_turn_mail_correlation",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."turn_mail_correlation" (
        "tenant_id" text NOT NULL,
        "mail_id" text NOT NULL,
        "workbench_id" text NOT NULL,
        "source_message_id" text NOT NULL,
        "recorded_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "mail_id")
      );
    `,
  },
  {
    // CL-7104: the RFC 5322 `Message-ID` a timeline row was dispatched
    // as. Derived from the row's own id, so there is nothing to
    // backfill: a row dispatched before this landed answers to the same
    // `<id@domain>` it always did, and a row that was never dispatched
    // stays null. Indexed for the inbound direction — a reply's
    // `In-Reply-To` names a Message-ID, and the row it belongs to is
    // found by that header, never by the sender's address.
    name: "0029_workbench_messages_mail_message_id",
    sql: `
      ALTER TABLE "chat"."workbench_messages"
        ADD COLUMN IF NOT EXISTS "mail_message_id" text;

      CREATE INDEX IF NOT EXISTS "workbench_messages_mail_message_id_idx"
        ON "chat"."workbench_messages" ("tenant_id", "mail_message_id");
    `,
  },
];

/**
 * Every folded run this package's own launches recorded in
 * `workbench_launch` (created as `channel_launch`; see the rename
 * migration below) — one row per workbench host or invited agent (see
 * `workbenchLaunch`'s own doc comment in `./schema.ts`). Exists for
 * `@corbits/folded-runs`' one-time backfill (CL-6061): before its own
 * `folded_run` marker table existed, this table was the only durable
 * record that a given run was folded. This package never writes to
 * `folded_runs.folded_run` itself — that would make it depend on a
 * package that already depends on it — so it only ever reads its own
 * schema and hands the ids back; the caller (scripts/db-setup.ts, the
 * one place that already knows every installed package) is the one
 * that inserts them as markers via `@corbits/folded-runs`' own export.
 */
export interface WorkbenchLaunchFoldedRunSeed {
  readonly id: string;
  readonly tenantId: string;
}

export async function listWorkbenchLaunchFoldedRunIds(
  databaseUrl: string,
): Promise<WorkbenchLaunchFoldedRunSeed[]> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    const rows = await sql.unsafe(
      `SELECT "current_run_id" AS "id", "tenant_id" AS "tenantId" FROM "chat"."workbench_launch"`,
    );
    return rows.map((row) => ({
      id: String(row["id"]),
      tenantId: String(row["tenantId"]),
    }));
  } finally {
    await sql.end();
  }
}

// Bookkeeping table for this package's own migrations. Named
// distinctly from the platform's setup ledger (`workbench_setup_migration`,
// in scripts/db-setup.ts) and from any drizzle journal, so extracting
// @corbits/chat out of this repo never has to disentangle its history
// from the platform's. Lives in the package's own `chat` schema, like
// every other table it owns.
const SCHEMA = "chat";
const LEDGER_TABLE = "chat_migrations";

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function quoteQualified(schema: string, name: string): string {
  return `${quoteIdentifier(schema)}.${quoteIdentifier(name)}`;
}

export interface ApplyChatMigrationsReport {
  applied: string[];
  alreadyApplied: string[];
}

/**
 * Apply `chatMigrations` against `databaseUrl`, idempotently: a
 * migration already recorded in the ledger is skipped, never re-run.
 * Failures are loud — the migration name and the underlying error are
 * both surfaced, since a partial apply here would otherwise fail
 * silently at the next `workbench setup`.
 */
export async function applyChatMigrations(
  databaseUrl: string,
): Promise<ApplyChatMigrationsReport> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    await sql.unsafe(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(SCHEMA)}`);

    await sql.unsafe(
      `CREATE TABLE IF NOT EXISTS ${quoteQualified(SCHEMA, LEDGER_TABLE)} (` +
        `name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`,
    );
    const rows = await sql.unsafe(
      `SELECT name FROM ${quoteQualified(SCHEMA, LEDGER_TABLE)}`,
    );
    const alreadyApplied = new Set(rows.map((row) => String(row["name"])));
    const applied: string[] = [];
    for (const migration of chatMigrations) {
      if (alreadyApplied.has(migration.name)) continue;
      try {
        await sql.begin(async (tx) => {
          await tx.unsafe(migration.sql);
          await tx.unsafe(
            `INSERT INTO ${quoteQualified(SCHEMA, LEDGER_TABLE)} (name) VALUES ($1)`,
            [migration.name],
          );
        });
        applied.push(migration.name);
      } catch (error) {
        throw new Error(
          `@corbits/chat migration ${JSON.stringify(migration.name)} failed: ` +
            `${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      }
    }
    return { applied, alreadyApplied: [...alreadyApplied] };
  } finally {
    await sql.end();
  }
}
